# Generated by Django 6.0.4 on 2026-07-14 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bingo',
            fields=[
                ('idbingo', models.AutoField(primary_key=True, serialize=False)),
                ('titulobingo', models.CharField(max_length=150)),
                ('fechaprogramadabingo', models.DateTimeField()),
                ('tipobingo', models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial')], max_length=20)),
                ('preciocarton', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premiomayor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcionpremiomayor', models.CharField(max_length=100)),
                ('estadobingo', models.CharField(choices=[('Programado', 'Programado'), ('En Curso', 'En Curso'), ('Finalizado', 'Finalizado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('idcarton', models.AutoField(primary_key=True, serialize=False)),
                ('codigocarton', models.CharField(max_length=30, unique=True)),
                ('matriznumeros', models.JSONField()),
                ('esmaestro', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMonetaria',
            fields=[
                ('idunidadmonetaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombremoneda', models.CharField(max_length=100)),
                ('tipomoneda', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Virtual', 'Virtual')], max_length=12)),
                ('simbolomoneda', models.CharField(max_length=255)),
                ('tasaconversionmoneda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estadomoneda', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('idjugador', models.AutoField(primary_key=True, serialize=False)),
                ('nombresjugador', models.CharField(blank=True, max_length=100, null=True)),
                ('aliasjugador', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecharegistrojugador', models.DateTimeField(auto_now_add=True)),
                ('saldocreditojugador', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldovirtualjugador', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estadocuentajugador', models.CharField(default='Activo', max_length=20)),
                ('usuario_django', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartidaBingo',
            fields=[
                ('idpartidabingo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreronda', models.CharField(default='Ronda 1', max_length=100)),
                ('modalidadvictoria', models.CharField(default='Cartón Lleno', max_length=100)),
                ('valorpremio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('premiomaterial', models.CharField(default='Ninguno', max_length=150)),
                ('estadopremiomaterial', models.CharField(default='No Aplica', max_length=20)),
                ('estadopartida', models.CharField(default='Programado', max_length=20)),
                ('bolascantadas', models.JSONField(default=list)),
                ('ultimabola', models.IntegerField(default=0)),
                ('horainicio', models.DateTimeField(auto_now_add=True)),
                ('idbingo', models.ForeignKey(blank=True, db_column='idbingo', null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.bingo')),
                ('idjugadorganador', models.ForeignKey(blank=True, db_column='idjugadorganador', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='CartonPartidaBingo',
            fields=[
                ('idcartonpartida', models.AutoField(primary_key=True, serialize=False)),
                ('estadocarton', models.CharField(default='Vendido', max_length=20)),
                ('numerosmarcados', models.JSONField(default=list)),
                ('idcarton', models.ForeignKey(db_column='idcarton', on_delete=django.db.models.deletion.CASCADE, to='tareas.carton')),
                ('idjugador', models.ForeignKey(db_column='idjugador', on_delete=django.db.models.deletion.CASCADE, to='tareas.jugador')),
                ('idpartida', models.ForeignKey(db_column='idpartida', on_delete=django.db.models.deletion.CASCADE, to='tareas.partidabingo')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('important', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bingo',
            name='idunidadmonetaria',
            field=models.ForeignKey(db_column='idunidadmonetaria', on_delete=django.db.models.deletion.RESTRICT, to='tareas.unidadmonetaria'),
        ),
    ]
