# Generated by Django 6.0.4 on 2026-07-14 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='cedulaidentidadjugador',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener números, sin letras ni espacios.', regex='^\\d+$')]),
        ),
    ]
