# Generated by Django 6.0.4 on 2026-07-14 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_jugador_cedulaidentidadjugador'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('idmensaje', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('fechahora', models.DateTimeField(auto_now_add=True)),
                ('idbingo', models.ForeignKey(db_column='idbingo', on_delete=django.db.models.deletion.CASCADE, to='tareas.bingo')),
            ],
        ),
    ]
