# Generated by Django 6.0.4 on 2026-07-14 03:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_mensajechat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionWeb',
            fields=[
                ('idconfiguracion', models.AutoField(primary_key=True, serialize=False)),
                ('titulosobrenosotros', models.CharField(max_length=150)),
                ('descripcionsobrenosotros', models.TextField()),
                ('imagenpromocional', models.CharField(max_length=255)),
                ('numerowhatsapp', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener números, sin letras ni espacios.', regex='^\\d+$')])),
                ('enlaceinstagram', models.CharField(blank=True, max_length=255, null=True)),
                ('enlacefacebook', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaultimaactualizacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('idmetodopago', models.AutoField(primary_key=True, serialize=False)),
                ('nombremetodopago', models.CharField(max_length=50, unique=True)),
                ('descripcionmetodopago', models.CharField(blank=True, max_length=200, null=True)),
                ('estadometodopago', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=20)),
                ('urlmetodopago', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlataformaJuego',
            fields=[
                ('idplataformajuego', models.AutoField(primary_key=True, serialize=False)),
                ('nombreplataforma', models.CharField(max_length=25, unique=True)),
                ('logoplataforma', models.CharField(blank=True, max_length=255, null=True)),
                ('urlplataforma', models.CharField(max_length=255)),
                ('descripcionplataforma', models.CharField(blank=True, max_length=200, null=True)),
                ('estadoplataforma', models.BooleanField(default=True)),
                ('fechaadquisicionlicencia', models.DateField(blank=True, null=True)),
                ('fechavencimientolicencia', models.DateField(blank=True, null=True)),
                ('contactoplataforma', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('idprestamo', models.AutoField(primary_key=True, serialize=False)),
                ('montoprestamosolicitado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasainteres', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('montototalpagar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldopendiente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numerocuotas', models.PositiveIntegerField(default=1)),
                ('fechasolicitud', models.DateField()),
                ('fechavencimiento', models.DateField()),
                ('estadoprestamo', models.CharField(choices=[('Solicitado', 'Solicitado'), ('Aprobado', 'Aprobado'), ('En espera', 'En espera'), ('Liquidado', 'Liquidado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Regalo',
            fields=[
                ('idregalo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreregalo', models.CharField(max_length=100)),
                ('descripcionregalo', models.CharField(blank=True, max_length=200, null=True)),
                ('valorregalo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaentregaregalo', models.DateTimeField()),
                ('estadoregalo', models.CharField(choices=[('Acumulado', 'Acumulado'), ('Sorteado', 'Sorteado'), ('Entregado', 'Entregado')], max_length=20)),
                ('fechaultimaactualizacion', models.DateTimeField(blank=True, null=True)),
                ('urlimagen', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('idsocio', models.AutoField(primary_key=True, serialize=False)),
                ('primernombresocio', models.CharField(max_length=40)),
                ('segundonombresocio', models.CharField(blank=True, max_length=40, null=True)),
                ('primerapellidosocio', models.CharField(max_length=40)),
                ('segundoapellidosocio', models.CharField(max_length=40)),
                ('cisocio', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener números, sin letras ni espacios.', regex='^\\d+$')])),
                ('fotosocio', models.CharField(blank=True, max_length=255, null=True)),
                ('fechanacimientosocio', models.DateField()),
                ('telefonopersonalsocio', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener números, sin letras ni espacios.', regex='^\\d+$')])),
                ('telefonotrabajosocio', models.CharField(blank=True, max_length=25, null=True)),
                ('direcciondomiciliosocio', models.CharField(max_length=255)),
                ('direcciontrabajosocio', models.CharField(blank=True, max_length=255, null=True)),
                ('sexosocio', models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, null=True)),
                ('estadosocio', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSocio',
            fields=[
                ('idtiposocio', models.AutoField(primary_key=True, serialize=False)),
                ('nombretiposocio', models.CharField(max_length=100, unique=True)),
                ('roltiposocio', models.CharField(max_length=50, unique=True)),
                ('descripciondetiposocio', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idpago', models.AutoField(primary_key=True, serialize=False)),
                ('montopagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numeroreferencia', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fechapago', models.DateTimeField()),
                ('fechaconfirmacionadmin', models.DateTimeField(blank=True, null=True)),
                ('comprobantepago', models.CharField(max_length=255)),
                ('estadopago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Validado', 'Validado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('idmetodopago', models.ForeignKey(db_column='idmetodopago', on_delete=django.db.models.deletion.RESTRICT, related_name='pagos', to='tareas.metodopago')),
                ('idprestamo', models.ForeignKey(db_column='idprestamo', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='tareas.prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='SesionJuego',
            fields=[
                ('idsesion', models.AutoField(primary_key=True, serialize=False)),
                ('fechainiciosesion', models.DateTimeField()),
                ('fechafinsesion', models.DateTimeField(blank=True, null=True)),
                ('ipconexion', models.CharField(blank=True, max_length=50, null=True)),
                ('dispositivoconexion', models.CharField(blank=True, max_length=50, null=True)),
                ('estadosesion', models.CharField(choices=[('Activa', 'Activa'), ('Finalizada', 'Finalizada'), ('Caida', 'Caida')], max_length=15)),
                ('latenciaping', models.IntegerField(blank=True, null=True)),
                ('navegadorweb', models.CharField(blank=True, max_length=150, null=True)),
                ('tokenconexion', models.CharField(max_length=255, unique=True)),
                ('motivocierre', models.CharField(blank=True, max_length=50, null=True)),
                ('idjugador', models.ForeignKey(db_column='idjugador', on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='tareas.jugador')),
                ('idpartida', models.ForeignKey(db_column='idpartida', on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='tareas.partidabingo')),
                ('idplataforma', models.ForeignKey(db_column='idplataforma', on_delete=django.db.models.deletion.RESTRICT, related_name='sesiones', to='tareas.plataformajuego')),
            ],
        ),
        migrations.AddField(
            model_name='prestamo',
            name='idgarante1',
            field=models.ForeignKey(blank=True, db_column='idgarante1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_garante1', to='tareas.socio'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='idgarante2',
            field=models.ForeignKey(blank=True, db_column='idgarante2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_garante2', to='tareas.socio'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='idsocio',
            field=models.ForeignKey(db_column='idsocio', on_delete=django.db.models.deletion.RESTRICT, related_name='prestamos', to='tareas.socio'),
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('idcuentabancaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombrebanco', models.CharField(max_length=100)),
                ('numerocuenta', models.CharField(max_length=30, unique=True)),
                ('tipocuenta', models.CharField(choices=[('Ahorro', 'Ahorro'), ('Corriente', 'Corriente')], max_length=20)),
                ('esprincipal', models.BooleanField(default=False)),
                ('fecharegistro', models.DateTimeField(auto_now_add=True)),
                ('estadocuenta', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], max_length=10)),
                ('idsocio', models.ForeignKey(db_column='idsocio', on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='tareas.socio')),
            ],
        ),
        migrations.CreateModel(
            name='AporteSemanal',
            fields=[
                ('idaporte', models.AutoField(primary_key=True, serialize=False)),
                ('numerosemana', models.IntegerField(blank=True, null=True)),
                ('fechaplanificadada', models.DateTimeField()),
                ('fechaentregareal', models.DateTimeField(blank=True, null=True)),
                ('metodoingreso', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Fisico', 'Fisico')], max_length=50)),
                ('referenciaingreso', models.CharField(blank=True, max_length=100, null=True)),
                ('estadoaporte', models.CharField(blank=True, choices=[('Al Dia', 'Al Dia'), ('Atrasado', 'Atrasado')], max_length=20, null=True)),
                ('idbingo', models.ForeignKey(blank=True, db_column='idbingo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aportes_semanales', to='tareas.bingo')),
                ('idregalo', models.ForeignKey(db_column='idregalo', on_delete=django.db.models.deletion.RESTRICT, related_name='aportes_semanales', to='tareas.regalo')),
                ('idsocio', models.ForeignKey(db_column='idsocio', on_delete=django.db.models.deletion.CASCADE, related_name='aportes_semanales', to='tareas.socio')),
            ],
        ),
        migrations.CreateModel(
            name='Ahorro',
            fields=[
                ('idahorro', models.AutoField(primary_key=True, serialize=False)),
                ('tipoahorro', models.CharField(choices=[('Obligatorio', 'Obligatorio'), ('Voluntario', 'Voluntario')], max_length=50)),
                ('montoahorro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaahorro', models.DateTimeField()),
                ('comentarioahorro', models.CharField(blank=True, max_length=100, null=True)),
                ('estadoahorro', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=25)),
                ('idbingo', models.ForeignKey(db_column='idbingo', on_delete=django.db.models.deletion.CASCADE, related_name='ahorros', to='tareas.bingo')),
                ('idsocio', models.ForeignKey(db_column='idsocio', on_delete=django.db.models.deletion.CASCADE, related_name='ahorros', to='tareas.socio')),
            ],
        ),
        migrations.AddField(
            model_name='socio',
            name='idtiposocio',
            field=models.ForeignKey(db_column='idtiposocio', on_delete=django.db.models.deletion.RESTRICT, related_name='socios', to='tareas.tiposocio'),
        ),
    ]
