# Generated by Django 6.0.4 on 2026-07-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_configuracionweb_metodopago_plataformajuego_prestamo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartonpartidabingo',
            name='cantidadaciertos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartonpartidabingo',
            name='esganador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartonpartidabingo',
            name='fechacompra',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cartonpartidabingo',
            name='fechaganador',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartonpartidabingo',
            name='preciopagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='partidabingo',
            name='bolamayordesempate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partidabingo',
            name='haydesempate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partidabingo',
            name='horafin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partidabingo',
            name='idbingadores',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='partidabingo',
            name='modalidadvictoria',
            field=models.CharField(choices=[('Tabla Llena', 'Tabla Llena'), ('Las Cuatro Esquinas', 'Las Cuatro Esquinas'), ('En Diagonal', 'En Diagonal'), ('Forma de X', 'Forma de X'), ('Forma de Cruz', 'Forma de Cruz'), ('Marco de Foto', 'Marco de Foto'), ('Línea Horizontal', 'Línea Horizontal'), ('Línea Vertical', 'Línea Vertical'), ('Forma de L', 'Forma de L'), ('Forma de C', 'Forma de C'), ('Forma de T', 'Forma de T'), ('Forma de U', 'Forma de U'), ('Forma de H', 'Forma de H'), ('Forma de Z', 'Forma de Z'), ('Forma de Flecha', 'Forma de Flecha')], default='Tabla Llena', max_length=100),
        ),
    ]
